# Generated by Django 5.1.3 on 2024-12-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('no8910', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promo',
        ),
        migrations.DeleteModel(
            name='Subkategori',
        ),
        migrations.AlterUniqueTogether(
            name='testimoni',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testimoni',
            name='transaksi',
        ),
        migrations.RemoveField(
            model_name='testimoni',
            name='user',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.DeleteModel(
            name='Transaksi',
        ),
        migrations.DeleteModel(
            name='Testimoni',
        ),
    ]
